FROM node:alpine

RUN yarn global add serve

# Npm install
COPY ./package.json /app/frontend/package.json
COPY ./yarn.lock /app/frontend/yarn.lock
WORKDIR /app/frontend
RUN yarn install --verbose

# Copy Source, Expose, Run Entry
COPY . /app/frontend/
EXPOSE 3000

CMD ./entrypoint.prod.sh
