FROM node:alpine

#Npm install
COPY ./package.json /app/frontend/package.json
COPY ./package-lock.json /app/frontend/package-lock.json
RUN cd /app/frontend; npm install

#
WORKDIR /app/frontend
COPY . /app/frontend/
EXPOSE 3000

CMD ./entrypoint.sh
