# Generated by Django 2.2 on 2019-05-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_auto_20190515_0152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='SupportItem',
        ),
    ]
