# Generated by Django 2.2 on 2019-05-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20190515_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgeting',
            old_name='count',
            new_name='numItems',
        ),
    ]
