FROM python:3.7-slim-stretch

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        default-libmysqlclient-dev \
        gcc \
        python3-dev \
        mysql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/ndis_calculator/requirements.txt
WORKDIR /app/ndis_calculator
RUN pip install -r requirements.txt
COPY . /app/ndis_calculator

EXPOSE 8000
